import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";

export const fancyFont = Playfair_Display({
  subsets: ["latin"],
  weight: ["600"],
});

export const metadata: Metadata = {
  title: "Pitch Perfect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fancyFont.className}`}>{children}</body>
    </html>
  );
}
